import { ThemeProvider} from "@material-tailwind/react";
const customTheme = {
  button: {
    valid: {
      colors: ["dark", "slate", "sky", "yellow", "blue", "green", "red"],
    },
    styles,
          // fontSize: "!text-sm",
        }
      },
      variants,
            color,
          },
          yellow,
            color,
          },
          blue,
            color,
          },
          green,
            color,
          },
          red,
            color,
          },
          slate,
            color,
          },
          dark,
            color,
          }
        },
        outlined,
            border,
          },
          yellow,
            border,
          },
          blue,
            border,
          },
          red,
            border,
          green,
            border,
          slate,
            border,
          dark,
            border,
        text,
      },
    },
  },
  iconButton,
    },
    styles,
            border,
          },
          yellow,
            border,
          },
          blue,
            border,
          },
          red,
            border,
          green,
            border,
          slate,
            border,
          dark,
            border,
        filled,
            color,

    },
  },
  checkbox,
    },
    styles,
            border,
  },
  navbar,
            color,
          },
          yellow,
            color,
          },
          blue,
            color,
          },
          green,
            color,
          },
          red,
            color,
          },
          slate,
            color,
          },
          dark,
            color,
          }
        }
      },
    },
    valid,
    }
  },

  card,
    },
    styles,
          yellow,
          blue,
          green,
          red,
          slate,
          dark,

  input, "slate", "sky", "yellow", "blue", "green", "red"],
    },
    styles,
      variants,
            border,
          },
          yellow,
            border,
          },
          blue,
            border,
          },
          red,
            border,
          green,
            border,
          slate,
            border,
          dark,
            border) {
  return (
    <MTThemeProvider value={customTheme}>{children}</MTThemeProvider>
  );
}

export default ThemeProvider;
